def get_dominant_palette_from_image_bytes(
    img_bytes: bytes, pallete_size: int
) -> list[int]: ...
def get_dominant_palette_from_image_path(
    img_path: str, pallete_size: int
) -> list[int]: ...
def limit_image_byte_size(img_bytes: bytes, limit: int) -> bytes: ...
